In [2]:
import numpy as np

In [3]:
def zipf(num_items, alpha) -> np.ndarray:
    """
    Generate a Zipf distribution for the given number of items and alpha parameter.
    Args:
        num_items (int): Number of items.
        alpha (float): Zipf distribution parameter.
    Returns:
        np.ndarray: Zipf distribution probabilities.
    """
    z = np.arange(1, num_items + 1)
    zipf_dist = 1 / (z**alpha)
    zipf_dist /= np.sum(zipf_dist)
    return zipf_dist

In [ ]:
class CacheEnv:
    def __init__(self, num_items: int, num_edges: int, alpha: float, edge_capacity: int = 2024, num_vehicles: int = 40):
        """
        Initialize the Cache Environment.
        Args:
            num_items (int): Number of items in the environment.
            num_edges (int): Number of edges in the environment.
            alpha (float): Zipf distribution parameter.
        """
        self.num_items = num_items
        self.num_edges = num_edges
        self.num_vehicles = num_vehicles
        self.alpha = alpha
        self.edge_capacity = edge_capacity
        self.cache = np.zeros((num_edges, num_items), dtype=np.int8)
        sample_request = np.random.choice(
            np.arange(num_items), 
            size=self.num_vehicles, 
        )
        request_frequencies =
        self.remaining_capacity = np.full(num_edges, edge_capacity, dtype=np.int32)

env = CacheEnv(num_items=1000, num_edges=5, alpha=1.0)

In [15]:
sample_request = np.random.choice(
    np.arange(100),
    size=40,
)
sample_request

array([ 6,  2, 50, 19,  7, 73, 23, 56, 87, 57, 98, 41, 61, 11, 97,  9,  3,
       49, 34, 96, 27, 20, 76, 41, 14, 22, 14, 52, 10, 78, 80, 51, 73, 97,
       80, 77, 27, 41, 18, 99])

In [21]:
frequencies = np.bincount(
    sample_request, 
    minlength=100
)
for idx, value in enumerate(frequencies):
    if value > 0:
        print(f"Item {idx} requested {value} times.")

Item 2 requested 1 times.
Item 3 requested 1 times.
Item 6 requested 1 times.
Item 7 requested 1 times.
Item 9 requested 1 times.
Item 10 requested 1 times.
Item 11 requested 1 times.
Item 14 requested 2 times.
Item 18 requested 1 times.
Item 19 requested 1 times.
Item 20 requested 1 times.
Item 22 requested 1 times.
Item 23 requested 1 times.
Item 27 requested 2 times.
Item 34 requested 1 times.
Item 41 requested 3 times.
Item 49 requested 1 times.
Item 50 requested 1 times.
Item 51 requested 1 times.
Item 52 requested 1 times.
Item 56 requested 1 times.
Item 57 requested 1 times.
Item 61 requested 1 times.
Item 73 requested 2 times.
Item 76 requested 1 times.
Item 77 requested 1 times.
Item 78 requested 1 times.
Item 80 requested 2 times.
Item 87 requested 1 times.
Item 96 requested 1 times.
Item 97 requested 2 times.
Item 98 requested 1 times.
Item 99 requested 1 times.


In [32]:
ranking = np.argsort(frequencies)[::-1]
ranking

array([41, 97, 73, 80, 27, 14, 96, 87, 77, 98, 78, 34, 56,  6,  7,  3, 11,
       76,  9, 18, 52, 49, 22, 20, 19, 23,  2, 99, 61, 57, 50, 51, 10, 88,
       95, 94, 64, 65, 66, 67, 68, 69, 70, 71, 72, 74, 75, 79, 84, 83, 82,
       81, 92, 93, 90, 91, 86, 85, 89, 55, 48, 58, 59, 60, 53, 54, 62, 63,
       32, 33, 35, 36, 38, 37, 39, 40, 46, 42, 43, 44, 47, 45, 29, 31, 16,
       17, 21, 30, 28, 26, 25, 24,  8, 15, 13, 12,  4,  5,  1,  0])

In [29]:
zipf_dist = zipf(100, 1.0)
zipf_dist

array([0.19277564, 0.09638782, 0.06425855, 0.04819391, 0.03855513,
       0.03212927, 0.02753938, 0.02409695, 0.02141952, 0.01927756,
       0.01752506, 0.01606464, 0.0148289 , 0.01376969, 0.01285171,
       0.01204848, 0.01133974, 0.01070976, 0.01014609, 0.00963878,
       0.00917979, 0.00876253, 0.00838155, 0.00803232, 0.00771103,
       0.00741445, 0.00713984, 0.00688484, 0.00664744, 0.00642585,
       0.00621857, 0.00602424, 0.00584169, 0.00566987, 0.00550788,
       0.00535488, 0.00521015, 0.00507304, 0.00494297, 0.00481939,
       0.00470184, 0.0045899 , 0.00448315, 0.00438126, 0.0042839 ,
       0.00419077, 0.00410161, 0.00401616, 0.0039342 , 0.00385551,
       0.00377991, 0.00370722, 0.00363728, 0.00356992, 0.00350501,
       0.00344242, 0.00338203, 0.00332372, 0.00326738, 0.00321293,
       0.00316026, 0.00310928, 0.00305993, 0.00301212, 0.00296578,
       0.00292084, 0.00287725, 0.00283494, 0.00279385, 0.00275394,
       0.00271515, 0.00267744, 0.00264076, 0.00260508, 0.00257

In [34]:
request_probs = np.zeros(100, dtype=np.float32)
request_probs[ranking] = zipf_dist
request_probs

array([0.00192776, 0.00194723, 0.00713984, 0.01204848, 0.00198738,
       0.0019671 , 0.01376969, 0.01285171, 0.00207286, 0.01014609,
       0.00584169, 0.01133974, 0.00200808, 0.00202922, 0.03212927,
       0.0020508 , 0.00226795, 0.00224158, 0.00963878, 0.00771103,
       0.00803232, 0.00221581, 0.00838155, 0.00741445, 0.00209539,
       0.00211841, 0.00214195, 0.03855513, 0.00216602, 0.0023226 ,
       0.00219063, 0.00229495, 0.00279385, 0.00275394, 0.01606464,
       0.00271515, 0.00267744, 0.00260508, 0.00264076, 0.00257034,
       0.00253652, 0.19277564, 0.00247148, 0.0024402 , 0.0024097 ,
       0.00235092, 0.00250358, 0.00237995, 0.00316026, 0.00876253,
       0.00621857, 0.00602424, 0.00917979, 0.00296578, 0.00292084,
       0.00321293, 0.0148289 , 0.00642585, 0.00310928, 0.00305993,
       0.00301212, 0.00664744, 0.00287725, 0.00283494, 0.00521015,
       0.00507304, 0.00494297, 0.00481939, 0.00470184, 0.0045899 ,
       0.00448315, 0.00438126, 0.0042839 , 0.06425855, 0.00419

Env - Current `(t)`
- init dummy last frequency (server known): `f(t-1)`
- init dummy cache of (t-1): `c(t-1)`
- use cache policy to update the cache (server known): `c(t)`
- compare `c(t)` with `c(t-1)` compute the cache replace cost: `cost_1(t)`
- init request probs from frequency (server unknown): `pop(t)`
- generate request from probs (server known): `req(t)`
- perform delivery in the small timescale to get the avg delivery delay and cost: `delay(t)`, `cost_2(t)`
- compute new frequency from request (server known): `f(t)`

State `s(t)`
- `f(t-1)`
- `c(t-1)`
- `pop(t)`
- `req(t)`
- `delay(t)`
- `cost_2(t)`